added webhook endpoint for success and expired stripe session
MaksymHorielikov/car-sharing-service pull request #36
Opened 2023-06-06 23:22 UTC by copypasterr

2023-06-07 08:45 UTC, KosMarch requested changes

2023-06-07 08:45 UTC, KosMarch commented on src/main/java/com/example/carsharingservice/config/StripeConfig.java
> +    @Value("${stripe.secret.endpoint}")
it is better to remove commented lines

2023-06-07 08:45 UTC, KosMarch commented on src/main/resources/application.properties
>  spring.jpa.hibernate.ddl-auto=validate
do not change the propriety

2023-06-09 05:42 UTC, MaksymHorielikov approved these changes

2023-06-09 06:06 UTC, KosMarch approved these changes

2023-06-15 08:46 UTC, merged